spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/central_book?useTimezone=true&serverTimezone=UTC
#    username: root
#    password: Password123#@!
    url: jdbc:mysql://root:-Bhh1fbb2B5A6f6gA6hh22cDHfheG24H@mysql.railway.internal:3306/railway
    username: root
    password: -Bhh1fbb2B5A6f6gA6hh22cDHfheG24H
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true

springdoc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true